- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'myapp', '--image', 'gcr.io/cicd-serverless/myapp:latest', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
